services:
  projectmanagementwebui:
    build:
      dockerfile: Dockerfile
    platform: linux/amd64
    image: chicong42/projectmanagementwebui
    ports:
      - "3000:3000"
    environment:
      - VITE_REQUEST_API_URL=http://118.70.171.240:9301/
